---
- hosts: all
  become: true
  tasks:
    - name: stop container
      shell: docker container stop tomcat-deplyment:latest
    - name: remove container
      shell: docker container rm tomcat-deplyment:latest
    - name: remove docker image
      shell: docker image rm rakeshnaik0908/tomcat-deplyment:latest
    - name: new container
      shell: docker run -itd --name tomcat-deplyment -p 8085:8080 rakeshnaik0908/tomcat-deplyment:latest
